export const unityBlendshapes = [
    { index : 0, name : 'Face_[01]'   , AUid : "1" },
    { index : 1, name : 'Face_[02]'   , AUid : "2" },
    { index : 2, name : 'Face_[02R]'  , AUid : "2R" },
    { index : 3, name : 'Face_[02L]'  , AUid : "2L" },
    { index : 4, name : 'Face_[04]'   , AUid : "4" },
    { index : 5, name : 'Face_[05]'   , AUid : "5" },
    { index : 6, name : 'Face_[06]'   , AUid : "6" },
    { index : 7, name : 'Face_[07]'   , AUid : "7" },
    { index : 8, name : 'Face_[08]'   , AUid : "8" },
    { index : 9, name : 'Face_[09]'   , AUid : "9" },
    { index : 10, name : 'Face_[10]'  , AUid : "10" },
    { index : 11, name : 'Face_[11]'  , AUid : "11" },
    { index : 12, name : 'Face_[12]'  , AUid : "12" },
    { index : 13, name : 'Face_[13]'  , AUid : "13" },
    { index : 14, name : 'Face_[14]'  , AUid : "14" },
    { index : 15, name : 'Face_[15]'  , AUid : "15" },
    { index : 16, name : 'Face_[16]'  , AUid : "16" },
    { index : 17, name : 'Face_[17]'  , AUid : "17" },
    { index : 18, name : 'Face_[18]'  , AUid : "18" },
    { index : 19, name : 'Face_[19]'  , AUid : "19" },
    { index : 20, name : 'Face_[20]'  , AUid : "20" },
    { index : 21, name : 'Face_[21]'  , AUid : "21" },
    { index : 22, name : 'Face_[22]'  , AUid : "22" },
    { index : 23, name : 'Face_[23]'  , AUid : "23" },
    { index : 24, name : 'Face_[24]'  , AUid : "24" },
    { index : 25, name : 'Face_[25]'  , AUid : "25" },
    { index : 26, name : 'Face_[26]'  , AUid : "26" },
    { index : 27, name : 'Face_[27]'  , AUid : "27" },
    { index : 28, name : 'Face_[28]'  , AUid : "28" },
    { index : 29, name : 'Face_[29]'  , AUid : "29" },
    { index : 30, name : 'Face_[30R]' , AUid : "30R" },
    { index : 31, name : 'Face_[30L]' , AUid : "30L" },
    { index : 32, name : 'Face_[31]'  , AUid : "31" },
    { index : 33, name : 'Face_[32]'  , AUid : "32" },
    { index : 34, name : 'Face_[33]'  , AUid : "33" },
    { index : 35, name : 'Face_[34]'  , AUid : "34" },
    { index : 36, name : 'Face_[35]'  , AUid : "35" },
    { index : 37, name : 'Face_[36L]' , AUid : "36L" },
    { index : 38, name : 'Face_[36R]' , AUid : "36R" },
    { index : 39, name : 'Face_[37]'  , AUid : "37" },
    { index : 40, name : 'Face_[38]'  , AUid : "38" },
    { index : 41, name : 'Face_[39]'  , AUid : "39" },
    { index : 42, name : 'Face_[41]'  , AUid : "41" },
    { index : 43, name : 'Face_[42]'  , AUid : "42" },
    { index : 44, name : 'Face_[43]'  , AUid : "43" },
    { index : 45, name : 'Face_[44]'  , AUid : "44" },
    { index : 46, name : 'Face_[45]'  , AUid : "45" },
    { index : 47, name : 'Face_[46R]' , AUid : "46R" },
    { index : 48, name : 'Face_[46L]' , AUid : "46L" },
    { index : 49, name : 'Face_[65]'  , AUid : "65" },
    { index : 50, name : 'Face_[neutral_viseme]' },
    { index : 51, name : 'Face_[ae_ax_ah]'       , VisemeName : "ae ax ah"   },
    { index : 52, name : 'Face_[aa]'             , VisemeName : "aa"         },
    { index : 53, name : 'Face_[ao]'             , VisemeName : "ao"         },
    { index : 54, name : 'Face_[ey_eh_uh]'       , VisemeName : "ey eh uh"   },
    { index : 55, name : 'Face_[er]'             , VisemeName : "er"         },
    { index : 56, name : 'Face_[y_iy_ih_ix]'     , VisemeName : "y iy ih ix" },
    { index : 57, name : 'Face_[w_uw]'           , VisemeName : "w uw"       },
    { index : 58, name : 'Face_[ow]'             , VisemeName : "ow"         },
    { index : 59, name : 'Face_[aw]'             , VisemeName : "aw"         },
    { index : 60, name : 'Face_[oy]'             , VisemeName : "oy"         },
    { index : 61, name : 'Face_[ay]'             , VisemeName : "ay"         },
    { index : 62, name : 'Face_[h]'              , VisemeName : "h"          },
    { index : 63, name : 'Face_[r]'              , VisemeName : "r"          },
    { index : 64, name : 'Face_[l]'              , VisemeName : "l"          },
    { index : 65, name : 'Face_[s_z]'            , VisemeName : "s z"        },
    { index : 66, name : 'Face_[sh_ch_jh_zh]001' , VisemeName : "sh ch jh zh"},
    { index : 67, name : 'Face_[th_dh]'          , VisemeName : "th dh"      },
    { index : 68, name : 'Face_[f_v]'            , VisemeName : "f v"        },
    { index : 69, name : 'Face_[d_t_n]'          , VisemeName : "d t n"      },
    { index : 70, name : 'Face_[f_v]001'         , VisemeName : "k g ng"     },
    { index : 71, name : 'Face_[p_b_m]'          , VisemeName : "p b m"      }
];

export const unityBoneshapes = [
    { index :  0, name : 'Face_51'  , AUid : "51" },
    { index :  1, name : 'Face_52'  , AUid : "52" },
    { index :  2, name : 'Face_53'  , AUid : "53" },
    { index :  3, name : 'Face_54'  , AUid : "54" },
    { index :  4, name : 'Face_55'  , AUid : "55" },
    { index :  5, name : 'Face_56'  , AUid : "56" },
    { index :  6, name : 'Face_57'  , AUid : "57" },
    { index :  7, name : 'Face_58'  , AUid : "58" },
    { index :  8, name : 'Face_61'  , AUid : "61" },
    { index : 11, name : 'Face_62'  , AUid : "62" },
    { index : 13, name : 'Face_63'  , AUid : "63" },
    { index : 14, name : 'Face_64'  , AUid : "64" },
    { index : 17, name : 'Face_66'  , AUid : "66" }
    
]
export const ActionUnitsList = [
    { id : "0"   , name : "neutralFace"},          //Main Codes
    { id : "1"   , name : "innerBrowRaiser"},
    { id : "2"   , name : "outerBrowRaiser"},
    { id : "2L"  , name : "outerBrowRaiserL"},
    { id : "2R"  , name : "outerBrowRaiserR"},
    { id : "4"   , name : "browLowerer"},
    { id : "5"   , name : "upperLidRaiser"},
    { id : "6"   , name : "cheekRaiser"},
    { id : "7"   , name : "lidTightener"},
    { id : "8"   , name : "lipsTowardEachOther"},
    { id : "9"   , name : "noseWrinkler"},
    { id : "10"  , name : "upperLipRaiser"},
    { id : "11"  , name : "nasolabialDeepener"},
    { id : "12"  , name : "lipCornerPuller"},
    { id : "13"  , name : "sharpLipPuller"},
    { id : "14"  , name : "dimpler"},
    { id : "15"  , name : "lipCornerDepressor"},
    { id : "16"  , name : "lowerLipDepressor"},
    { id : "17"  , name : "chinRaiser"},
    { id : "18"  , name : "lipPucker"},
    { id : "19"  , name : "tongueShow"},
    { id : "20"  , name : "lipStretcher"},
    { id : "21"  , name : "neckTightener"},
    { id : "22"  , name : "lipFunneler"},
    { id : "23"  , name : "lipTightener"},
    { id : "24"  , name : "lipPressor"},
    { id : "25"  , name : "lipsPart"},
    { id : "26"  , name : "jawDrop"},
    { id : "27"  , name : "mouthStretch"},
    { id : "28"  , name : "lipSuck"},
    { id : "29"  , name : "jawThrust"},
    { id : "30L"  , name : "jawSidewaysLeft"},
    { id : "30R"  , name : "jawSidewaysRight"},
    { id : "31"  , name : "jawClencher"},
    { id : "32"  , name : "lipBite"},
    { id : "33"  , name : "cheekBlow"},
    { id : "34"  , name : "cheekPuff"},
    { id : "35"  , name : "cheekSuck"},
    { id : "36"  , name : "tongueBulge"},
    { id : "36L"  , name : "tongueBulge L"},
    { id : "36R"  , name : "tongueBulge R"},
    { id : "37"  , name : "lipWipe"},
    { id : "38"  , name : "nostrilDilator"},
    { id : "39"  , name : "nostilCompressor"},
    { id : "41"  , name : "glabellaLowerer"},
    { id : "42"  , name : "innerEyebrowLowerer"},
    { id : "43"  , name : "eyesClosed"},
    { id : "44"  , name : "eyebrowGatherer"},
    { id : "45"  , name : "blink"},
    { id : "46R" , name : "winkR"},
    { id : "46L" , name : "winkL"},
    { id : "51"  , name : "headTurnLeft"                 },            //Head Movement Codes
    { id : "52"  , name : "headTurnRight"                },
    { id : "53"  , name : "headUp"                       },
    { id : "54"  , name : "headDown"                     },
    { id : "55"  , name : "headTiltLeft"                 },
    { id : "M55" , name : "headTiltLeftBis"              },
    { id : "56"  , name : "headTiltRight"                },
    { id : "M56" , name : "headTiltRightBis"             },
    { id : "57"  , name : "headForward"                  },
    { id : "M57" , name : "headForwardBis"               },
    { id : "58"  , name : "headBack"                     },
    { id : "M59" , name : "headShakeUpAndDown"           },
    { id : "M60" , name : "headShakeSideToSide"          },
    { id : "M83" , name : "headUpwardAndTheSide"         },
    { id : "61"  , name : "eyesTurnLeft"                 },               //Eye Movement Codes
    { id : "M61" , name : "eyesLeft"                     },
    { id : "62"  , name : "eyesTurnRight"                },
    { id : "M62" , name : "eyesRight"                    },
    { id : "63"  , name : "eyesUp"                       },
    { id : "64"  , name : "eyesDown"                     },
    { id : "65"  , name : "walleye"                      },
    { id : "66"  , name : "crosseye"                     },
    { id : "M68" , name : "upwardRollingEyes"            },
    { id : "69"  , name : "eyesPositionedOtherPerson"    },
    { id : "M69" , name : "headEyesPositionedOtherPerson"}
];

export const EmotionsList = [
    { name : "Neutral"    , code : ""               },
    { name : "Happiness" , code : "6+12"           },
    { name : "Sadness"   , code : "1+4+15"         },
    { name : "Surprise"  , code : "1+2+5B+26"      },
    { name : "Fear"      , code : "1+2+4+5+7+20+26"},
    { name : "Anger"     , code : "4+5+7+23"       },
    { name : "Disgust"   , code : "9+15+16"        },
    { name : "Contempt"  , code : "R12A+R14A"      }
]

export const VisemesList = [ // id is useless, TODO remove
    { id : 0  , name : "ae ax ah"   },
    { id : 1  , name : "aa"         },
    { id : 2  , name : "ao"         },
    { id : 3  , name : "ey eh uh"   },
    { id : 4  , name : "er"         },
    { id : 5  , name : "y iy ih ix" },
    { id : 6  , name : "w uw"       },
    { id : 7  , name : "ow"         },
    { id : 8  , name : "aw"         },
    { id : 9  , name : "oy"         },
    { id : 10 , name : "ay"         },
    { id : 11 , name : "h"          },
    { id : 12 , name : "r"          },
    { id : 13 , name : "l"          },
    { id : 14 , name : "s z"        },
    { id : 15 , name : "sh ch jh zh"},
    { id : 16 , name : "th dh"      },
    { id : 17 , name : "f v"        },
    { id : 18 , name : "d t n"      },
    { id : 19 , name : "k g ng"     },
    { id : 20 , name : "p b m"      }
]

    
	/* Currently missing
		{ id : "M55" , name : "headTiltLeftBis"              },
		{ id : "M56" , name : "headTiltRightBis"             },
		{ id : "M57" , name : "headForwardBis"               },
		{ id : "M59" , name : "headShakeUpAndDown"           },
		{ id : "M60" , name : "headShakeSideToSide"          },
		{ id : "M61" , name : "eyesLeft"                     },
		{ id : "M62" , name : "eyesRight"                    },
		{ id : "65"  , name : "walleye"                      },
		{ id : "M68" , name : "upwardRollingEyes"            },
		{ id : "69"  , name : "eyesPositionedOtherPerson"    },
		{ id : "M69" , name : "headEyesPositionedOtherPerson"}
		{ id : "M83" , name : "headUpwardAndTheSide"         },

	*/
	